

export const metadata = {
  title: "Blog List",
  description: "Generated by Me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        //tat ca cac file ben trong thu muc blogs dc render vao cho thg children
        <> {children} </>
  );
}
